// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA18YqV_OlDBeAmYKzAzbEaMeZSS8STkkY',
    appId: '1:109227591523:web:8dbc82678d025b2005f556',
    messagingSenderId: '109227591523',
    projectId: 'chatapptute-fe17d',
    authDomain: 'chatapptute-fe17d.firebaseapp.com',
    storageBucket: 'chatapptute-fe17d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS00okgA6iq5Dn8t41Um42HmtX_z3trDE',
    appId: '1:109227591523:android:e6c8bcb48ebf3a9c05f556',
    messagingSenderId: '109227591523',
    projectId: 'chatapptute-fe17d',
    storageBucket: 'chatapptute-fe17d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy1fL5Ga4TjLzE1vSd3zrPeCR1EaGNjU0',
    appId: '1:109227591523:ios:0aacc0e74a09f83d05f556',
    messagingSenderId: '109227591523',
    projectId: 'chatapptute-fe17d',
    storageBucket: 'chatapptute-fe17d.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy1fL5Ga4TjLzE1vSd3zrPeCR1EaGNjU0',
    appId: '1:109227591523:ios:780f2b43f0b1bf0005f556',
    messagingSenderId: '109227591523',
    projectId: 'chatapptute-fe17d',
    storageBucket: 'chatapptute-fe17d.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
